---
version: 1.4.10-6
default-factions-plugin: FactionsPro
enable-multiworld-chat: false
groups:
  Player:
    chat: '{PLAYER} §9{display_name} §e>> §7{msg}'
    nametag: ' {display_name}'
    worlds: []
  Helper:
    chat: '{HELPER} §d{display_name} §e>> §a{msg}'
    nametag: ' {display_name}'
    worlds: []
  Staff:
    chat: '{STAFF} §c{display_name} §e>> §b{msg}'
    nametag: ' {display_name}'
    worlds: []
...
